services:
  - type: web
    name: e-commerce-apis
    runtime: openjdk
    region: singapore
    plan: free
    rootDir: ecommerce-apis
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
    autoDeploy: true
    envVars:
      - key: JAVA_VERSION
        value: "17"
      - key: JWT_SECRET
        value: your_secret_key_here
